Blog_demo/Blog_demo/urls.py
from django.contrib import admin
from django.urls import path, include
from author import views as author_views

urlpatterns = [
    path("", include("blog.urls")),
    path("admin/", admin.site.urls),
    # path("blog/", include("blog.urls")),
    path("author/", include("author.urls")),
]

Blog_demo/author/urls.py
from django.urls import path
from . import  views

app_name = 'author'

urlpatterns = [
    path('index', views.index, name='index'),
    path('login', views.a_login, name='login'),
    path('register/', views.register, name='register'),
    path('captcha', views.send_email, name='email_captcha'),
    path('logout', views.a_logout, name='logout'),
    path('upload_image/', views.upload_image, name='upload_image'),
]

Blog_demo/blog/urls.py
from django.urls import path
from . import  views

app_name = 'blog'

urlpatterns = [
    path("", views.index, name="index"),
    path("blog/detail/<int:blog_id>", views.blog_detail, name="blog_detail"),
    path("blog/post", views.post_blog, name="post"),
    path("blog/comment/post", views.post_comment, name="post_comment"),
    path("search", views.search, name="search_blog"),
]

Blog_demo/author/models.py
from enum import unique

from django.db import models

# Create your models here.
class CaptchaModel(models.Model):
    email = models.EmailField(unique=True)
    captcha = models.CharField(max_length=6)
    create_time = models.DateTimeField(auto_now_add=True)

Blog_demo/blog/models.py
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()

# Create your models here.
class BlogCategory(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name

class Blog(models.Model):
    title = models.CharField(max_length=200)
    content = models.TextField()
    pub_time = models.DateTimeField(auto_now_add=True)
    category = models.ForeignKey(BlogCategory, on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['-pub_time']

class BlogComment(models.Model):
    content = models.TextField()
    pub_time = models.DateTimeField(auto_now_add=True)
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE, related_name='comments')
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.content

    class Meta:
        ordering = ['-pub_time']

Blog_demo/author/views.py
import string
import random
import re

from django.shortcuts import render, redirect
from django.http.response import JsonResponse
from django.core.mail import send_mail
from .models import CaptchaModel
from django.views.decorators.http import require_http_methods
from .forms import RegisterForm,LoginForm
from django.contrib.auth import get_user_model,login,logout
from django.views.decorators.csrf import csrf_exempt
from django.http import JsonResponse
from django.core.files.storage import FileSystemStorage

User = get_user_model()


# Create your views here.
@require_http_methods(['GET', 'POST'])
def a_login(request):
    if request.method == 'GET':
        return render(request, 'login.html')
    else:
        form = LoginForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data.get('email')
            password = form.cleaned_data.get('password')
            remember = form.cleaned_data.get('remember')
            user = User.objects.filter(email=email).first()
            if user and user.check_password(password):
                # login
                login(request, user)
                # judge if the user needs to remember me
                if not remember:
                    # If not click, then need to log in again when the browser closes
                    request.session.set_expiry(0)
                # If clicked, nothing is done, using the default two-week expiration time
                return redirect('/')
            else:
                print("Email or password error")
                form.add_error('email', 'Email or password error')
                return render(request, 'login.html', {'form': form})
        else:
            return render(request, 'login.html', {'form': form})


@require_http_methods(['GET', 'POST'])
def register(request):
    if request.method == 'GET':
        return render(request, 'register.html')
    else:
        form = RegisterForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data.get('email')
            password = form.cleaned_data.get('password')
            username = form.cleaned_data.get('username')
            User.objects.create_user(username=username, email=email, password=password)
            return render(request, 'login.html', {'form': form})
        else:
            print(form.errors)
            return render(request, 'register.html', {'form': form})


def index(request):
    return render(request, 'index.html')


def send_email(request):
    email = request.GET.get('email')

    # A regular expression used to validate the mailbox
    email_regex = r'^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$'

    # Check if the mailbox is empty or formatted incorrectly
    if not email or not re.match(email_regex, email):
        return JsonResponse({"code": 400, "message": 'Please enter a valid email address.'})

    # Generate a 6-digit verification code
    captcha = "".join(random.sample(string.digits, 6))

    # Save the verification code to the database
    CaptchaModel.objects.update_or_create(email=email, defaults={'captcha': captcha})

    # Send an email with a verification code
    send_mail(
        "AOA Blog Registration Verification",
        message=f"Your verification code is: {captcha}",
        from_email=None,
        recipient_list=[email]
    )

    return JsonResponse({"code": 200, "message": "Verification Code Sent Successfully"})

def a_logout(request):
    logout(request)
    return redirect('/')

@csrf_exempt
def upload_image(request):
    if request.method == 'POST' and request.FILES['image']:
        image = request.FILES['image']
        fs = FileSystemStorage()
        filename = fs.save(image.name, image)  # 保存文件
        # 在这里可以添加更新用户头像的逻辑
        return JsonResponse({'message': 'Image uploaded successfully!', 'filename': filename})
    return JsonResponse({'error': 'Invalid request'}, status=400)

Blog_demo/blog/views.py
from django.urls.base import reverse_lazy
from django.shortcuts import render, redirect, reverse
from django.http.response import JsonResponse
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_http_methods,require_POST, require_GET
from .models import BlogCategory, Blog, BlogComment
from .forms import PublishForm
from django.db.models import Q

# Create your views here.
def index(request):
    blogs = Blog.objects.all()
    return render(request, 'index.html', context={"blogs": blogs})

def blog_detail(request, blog_id):
    try:
        blog = Blog.objects.get(pk=blog_id)
    except Exception as e:
        blog = None
    return render(request, 'blog_detail.html', context={'blog': blog})

@require_http_methods(['GET', 'POST'])
@login_required(login_url=reverse_lazy("author:login"))
def post_blog(request):
    if request.method == 'GET':
        category = BlogCategory.objects.all()
        return render(request, 'post_blog.html', context={'category': category})
    else:
        form = PublishForm(request.POST)
        if form.is_valid():
            title = form.cleaned_data.get('title')
            content = form.cleaned_data.get('content')
            category_id = form.cleaned_data.get('category')
            content_2 = form.cleaned_data.get('content_2')
            print(content,content_2)
            blog = Blog.objects.create(title=title, content=content, category_id=category_id, author=request.user)
            return JsonResponse({"code": 200, "message": "Post success", "data": {"blog_id": blog.id}})
        else:
            return JsonResponse({"code":400, "message":form.errors})

@require_POST
@login_required(login_url=reverse_lazy("author:login"))
def post_comment(request):
    blog_id = request.POST.get('blog_id')
    content = request.POST.get('content')
    print(1)
    BlogComment.objects.create(blog_id=blog_id, content=content, author=request.user)

    #reload this page
    return redirect(reverse('blog:blog_detail', kwargs={"blog_id":blog_id}))

@require_GET
def search(request):
    # /search?q=xxx
    q = request.GET.get('q')
    # 从博客的标题和内容中查找含有q关键字的博客
    blogs = Blog.objects.filter(Q(title__icontains=q)|Q(content__icontains=q)).all()
    return render(request, 'index.html', context={"blogs": blogs})

Blog_demo/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'bootstrap5/bootstrap.min.css' %}">
    {#    <script#}
    {#            src="https://code.jquery.com/jquery-3.6.0.min.js"#}
    {#            integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="#}
    {#            crossorigin="anonymous"#}
    {#    ></script>#}
    {#        <script src="{% static 'bootstrap5/popper.min.js' %}"></script>#}
    <script
            src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js"
            integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB"
            crossorigin="anonymous"
    ></script>
    <script src="{% static 'bootstrap5/bootstrap.min.js' %}"></script>
    {#    <script#}
    {#            src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js"#}
    {#            integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13"#}
    {#            crossorigin="anonymous"#}
    {#    ></script>#}
    <link rel="stylesheet" href="{% static 'base.css' %}">

    {% block head %}{% endblock %}

    <script>
        function uploadImage() {
            document.getElementById('imageUploadInput').click();
        }

        async function handleFileSelect(event) {
            const file = event.target.files[0];
            if (file) {
                const formData = new FormData();
                formData.append('image', file);

                try {
                    const response = await fetch('{% url "author:upload_image" %}', {
                        method: 'POST',
                        body: formData,
                        headers: {
                            'X-CSRFToken': '{{ csrf_token }}' // Django CSRF token
                        }
                    });

                    if (response.ok) {
                        alert('Image uploaded successfully!');
                        // 这里可以添加其他操作，比如更新页面显示新头像
                    } else {
                        alert('Upload failed!');
                    }
                } catch (error) {
                    console.error('Error uploading image:', error);
                }
            }
        }
    </script>
</head>
<body>
<header class="p-3 text-bg-dark border-bottom mb-3">
    <div class="container">
        <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
            <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
                <img src="{% static 'images/img.png' %}" alt="logo" width="100" height="50">
            </a>

            <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
                <li><a href="{% url 'blog:index' %}" class="nav-link px-2 text-light">Home</a></li>
                <li><a href="{% url 'blog:post' %}" class="nav-link px-2 text-light">Post</a></li>
            </ul>

            <form class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3" role="search" action="{% url 'blog:search_blog' %}">
                <input type="search" name="q" class="form-control" placeholder="To Search..." aria-label="Search">
            </form>

            {% if user.is_authenticated %}
                <div class="dropdown text-end">
                    <a href="#" class="d-block link-body-emphasis text-decoration-none dropdown-toggle"
                       data-bs-toggle="dropdown" aria-expanded="false">
                        <img src="{% static 'images/img_1.png' %}" alt="mdo" width="32" height="32"
                             class="rounded-circle">
                        <span style="color: white">{{ user.username }}</span>
                    </a>
                    <ul class="dropdown-menu text-small" style="">
                        <li><a class="dropdown-item" href="#" onclick="uploadImage()">Upload Image</a></li>
                        <li><a class="dropdown-item" href="{% url 'author:logout' %}">Log out</a></li>
                    </ul>
                </div>
            {% else %}
                <div class="text-end">
                    <a href="{% url 'author:login' %}" type="button" class="btn btn-outline-primary me-2">Login</a>
                    <a href="{% url 'author:register' %}" type="button" class="btn btn-primary">Register</a>
                </div>
            {% endif %}
        </div>
    </div>
</header>
<main class="container bg-dark p-3 text-light rounded">
    {% block main %}{% endblock %}
</main>
</body>
</html>

Blog_demo/templates/blog_detail.html
{% extends 'base.html' %}

{% block title %}AOA Blog{% endblock %}

{% block main %}
    <h1>{{ blog.title }}</h1>
    <hr>
    <div class="mt-2">
        <img src="{% static 'images/img_1.png' %}" class="rounded-circle" alt="logo" width="30" height="30"></img>
        <span class="ms-2">{{ blog.author }}</span>
        <span class="ms-2">Posted on</span>
        <span class="ms-2">{{ blog.pub_time|date:"Y.m.d H.i.s" }}</span>
    </div>
    <hr>
    <div class="py-2">
        {{ blog.content|safe }}
    </div>
    <hr>
    <div class="mt-2">
        <h3>Comment({{ blog.comments.all|length }})</h3>
        <form action="{% url 'blog:post_comment' %}" method="POST">
            {% csrf_token %}
            <input type="hidden" name="blog_id" value="{{ blog.id }}">
            <div class="mt-2">
                <input type="text" class="form-control" placeholder="Please Enter Your Comment" name="content">
            </div>
            <div class="text-end mt-2">
                <button type="submit" class="btn btn-primary">Comment</button>
            </div>
        </form>
    </div>

    <div class="mt-2" >
        <ul class="list-group-flush list-group">
            {% for comment in blog.comments.all %}
                <li class="list-group-item">
                  <div class="d-flex justify-content-between">
                      <div class="user-info ">
                          <img src="{% static 'images/img_1.png' %}" class="rounded-circle" width="40" height="40" alt="">
                          <span class="ms-2">{{ comment.author.username }}</span>
                      </div>
                      <div class="create-time" style="line-height: 40px;">{{ comment.pub_time|date:"Y.m.d H.i.s" }}</div>
                  </div>
                  <div class="mt-2">{{ comment.content }}</div>
              </li>
            {% endfor %}
        </ul>
    </div>

{% endblock %}

Blog_demo/templates/index.html
{% extends 'base.html' %}

{% block title %}Index{% endblock %}

{% block main %}
	<h1>Blog List</h1>
    <div class="row row-cols-2 row-gap-4">
    {% for blog in blogs %}
        <div class="col">
            <div class="card">
                <div class="card-header">
                    <a href="{% url 'blog:blog_detail' blog_id=blog.id %}" style="text-decoration: none; color: inherit;">{{ blog.title }}</a>
                </div>
                <div class="card-body" style="height: 100px;">
                    <p class="card-text">{{ blog.content|striptags|truncatechars:200 }}</p>
                </div>
                <div class="card-footer text-body-secondary d-flex justify-content-between">
                    <div>
                        <img src="{% static 'images/img_1.png' %}" class="rounded-circle" width="30" height="30" alt="">
                        {{ blog.author.username }}
                    </div>
                    <div>{{ blog.pub_time|date:"Y.m.d H.i.s" }}</div>
                </div>
            </div>
        </div>
    {% endfor %}
    </div>
{% endblock %}

Blog_demo/templates/login.html
{% extends 'base.html' %}

{% block title %}Login{% endblock %}

{% block main %}
    <div style="max-width: 330px;" class="m-auto">
        <h1 class="text-center">LOGIN</h1>
        <form method="POST">
            {% csrf_token %}
            <div class="mb-3">
                <label>Email</label>
                <input type="email" class="form-control" name="email" placeholder="Enter email" value="{{ form.email.value }}">
                {% if form.email.errors %}
                    <div class="text-danger">
                        {{ form.email.errors|join:', ' }}
                    </div>
                {% endif %}
            </div>
            <div class="mb-3">
                <label>Password</label>
                <input type="password" class="form-control" name="password" placeholder="Enter password">
                {% if form.password.errors %}
                    <div class="text-danger">
                        {{ form.password.errors|join:', ' }}
                    </div>
                {% endif %}
            </div>
            <div class="form-check mb-3">
                <input class="form-check-input" type="checkbox" name="remember" value="1" id="flexCheckDefault">
                <label class="form-check-label" for="flexCheckDefault">
                    Remember me
                </label>
            </div>
            <div class="mb-3">
                <button class="btn btn-primary w-100">Login</button>
            </div>
        </form>
    </div>
{% endblock %}

Blog_demo/templates/post_blog.html
{% extends 'base.html' %}

{% block title %}Post{% endblock %}

{% block head %}
    <script src="{% static 'jquery/jquery-3.7.1.min.js' %}"></script>
    <link rel="stylesheet" href="{% static 'wangeditor/style.css' %}"></link>
    <script src="{% static 'wangeditor/index.js' %}"></script>
    <script src="{% static 'js/pub_blog.js' %}"></script>
    <style>
        #editor-wrapper {
            border: 1px solid #ccc;
            z-index: 120; /* 按需定义 */
        }

        #toolbar-container {
            border-bottom: 1px solid #ccc;
        }

        #editor-container {
            height: 500px;
        }
    </style>
{% endblock %}

{% block main %}
    <h1>Post Blog</h1>
    <div class="mt-3">
        <form action="" method="post">
            {% csrf_token %}
            <div class="mb-3">
                <label for="title" class="form-label">Title</label>
                <input type="text" name="title" class="form-control" placeholder="Please Enter title" required>
            </div>
            <div class="mb-3">
                <label for="category" class="form-label">Category</label>
                <select name="category" class="form-select" id="category-select">
                    {% for cat in category %}
                        <option value="{{ cat.id }}">{{ cat.name }}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="mb-3">
                <label for="content" class="form-label">Content</label>
                <div id="editor-wrapper">
                    <div id="toolbar-container"><!-- 工具栏 --></div>
                    <div id="editor-container"><!-- 编辑器 --></div>
                </div>
            </div>
            <div class="mb-3 text-end">
                <button class="btn btn-primary" id="submit-btn">Submit</button>
            </div>
        </form>
    </div>
{% endblock %}

Blog_demo/templates/register.html
{% extends 'base.html' %}

{% block title %}Register{% endblock %}

{% block head %}
    <script src="{% static 'jquery/jquery-3.7.1.min.js' %}"></script>
    <script src="{% static 'js/register.js' %}"></script>
    <style>
        .error-message {
            color: red;
            font-size: 0.875em; /* Adjust size as needed */
        }
    </style>
{% endblock %}

{% block main %}
    <div style="max-width: 330px;" class="m-auto">
        <h1 class="text-center">REGISTER</h1>

        <form action="" method="POST">
            {% csrf_token %}
            <div class="mb-3">
                <label>Username</label>
                <input type="text" class="form-control" name="username" placeholder="Enter username" value="{{ form.username.value|default:'' }}">
                {% if form.username.errors %}
                    <span class="error-message">{{ form.username.errors|first }}</span>
                {% endif %}
            </div>
            <div class="mb-3">
                <label>Password</label>
                <input type="password" class="form-control" name="password" placeholder="Enter password">
                {% if form.password.errors %}
                    <span class="error-message">{{ form.password.errors|first }}</span>
                {% endif %}
            </div>
            <div class="mb-3">
                <label>Email</label>
                <input type="email" class="form-control" name="email" placeholder="Enter email" value="{{ form.email.value|default:'' }}">
                {% if form.email.errors %}
                    <span class="error-message">{{ form.email.errors|first }}</span>
                {% endif %}
            </div>
            <div class="mb-3">
                <label>Verification Code</label>
                <div class="input-group mb-3">
                    <input type="text" class="form-control" name="captcha" placeholder="Enter verification code" aria-label="Recipient's username" aria-describedby="button-addon2">
                    <button class="btn btn-outline-secondary" type="button" id="get_captcha">Get VCode</button>
                </div>
                {% if form.captcha.errors %}
                    <span class="error-message">{{ form.captcha.errors|first }}</span>
                {% endif %}
            </div>
            <div class="mb-3">
                <button class="btn btn-primary w-100">Login</button>
            </div>
        </form>
    </div>
{% endblock %}